# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
env: 
  CI: false
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  reactDeploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.13.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
    
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm ci
    
    - run: npm run build
    
    - uses: appleboy/scp-action@master
      env:
        HOST: '46.19.67.46'
        USERNAME: 'root'
        PORT: 22
        KEY: ${{ secrets.SSH }}
      with: 
        source: "build"
        target: "/var/www/sati.show"
        strip_components: 1
        
  strapiDeploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-project
        
    strategy:
      matrix:
        node-version: ['18.13.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      run: |
        ls
        
    - uses: appleboy/ssh-action@v0.1.7
      with:
        host: '46.19.67.46'
        username: 'root'
        key: ${{ secrets.SSH }}
        port: 22
        script: |
          source ~/.bashrc
          forever stopall
          rm -r /var/www/sati.show/my-project
          
    - uses: appleboy/scp-action@master
      env:
        HOST: '46.19.67.46'
        USERNAME: 'root'
        PORT: 22
        KEY: ${{ secrets.SSH }}
      with: 
        source: "./*"
        target: "/var/www/sati.show"
        
    - uses: appleboy/ssh-action@v0.1.7
      with:
        host: '46.19.67.46'
        username: 'root'
        key: ${{ secrets.SSH }}
        port: 22
        script: |
          source ~/.bashrc
          cd /var/www/sati.show
          ls -la
          chown -R root:root .
          ls -la
          cd my-project
          npm install
          npm run build
          forever start --minUptime 1000 --spinSleepTime 1000 -c "npm run develop" ./
